### ISSUE TITLE
Is PCH really supported?

### ISSUE THREAD

**Issue by manu-st** [playscale/stashed.io#10]
If I use -Yu"stdafx.h" command line option, it reports the job as unsupported? Is this expected?

**Comment by jsmouret** [comment]
It is expected if PDB generation (/Zi) is also enabled. See ([link](https://github.com/playscale/stashed.io/wiki/Stats#job-unsupported))

We support PCH and PDB but not both at the same time .
You can try to use /Z7 to embed the debug information in the object file and get proper caching.

Thank you

**Comment by manu-st** [comment]
Indeed, I thought I was reading ZI not Zi.
