### ISSUE TITLE
Favicon for Stashed

### ISSUE THREAD

**Issue by serge-nikulin** [playscale/stashed.io#15]
The local Stashed "website" does not have favicon and when I save a link to "favorites" toolbar, the link shows browser's generic icon. It would be nice to see a non-generic Stashed icon.

Thanks!

**Comment by Justin-Randall** [comment]
Confirmed with Edge. Security restrictions with Edge (and Windows Store Apps) prevented proper loading of the icon. A fix will be in the next release of Stashed (1.4.4). 

I'll leave this open until you have had a chance to confirm the fix.

Thanks for the report and happy Stashing!

**Comment by Justin-Randall** [comment]
Fixed in 1.4.4.

**Comment by serge-nikulin** [comment]
I have deleted the old bookmark and created a new one.  
I see the same generic icon (5-star) as before.  
What procedure should I follow to see the new icon?  

Thanks!

**Comment by Justin-Randall** [comment]
Thanks, @serge-nikulin for reporting and verifying the fix! 

Happy Stashing!
