### ISSUE TITLE
Case sensitivity

### ISSUE THREAD

**Issue by manu-st** [playscale/stashed.io#17]
Once in a while I have this warning which causes my build to fail as I treat warning as error:
```
>RandomFile.obj : warning LNK4206: precompiled type information not found; 'c:\dev\release\x64\stdafx.obj' not linked or overwritten; linking object as if no debug info [C:\Dev\project.vcxproj]
```

When I look at my object file, I notice 2 things:
- the file is named `randomfile.obj` instead of `RandomFile.obj`
- the file `randomefile.obj` is older than `stdafx.obj`

It could be related to issue #13 but what strikes me is the case of the file name. If I delete the file and rebuild, then a `RandomFile.obj` is generated with the proper case and link succeeds.

Any idea if this is a msbuild issue or msbuild + stashed.io issue?

Thanks!

**Comment by jsmouret** [comment]
We went a bit too far trying to standardize paths to work well with distributed builds. Let's revert that :)

Fix coming up in 1.4.5 later today.

**Comment by Justin-Randall** [comment]
Version 1.4.5 is now available. Please let us know if this has solved the issue.

**Comment by manu-st** [comment]
So far the .obj files preserve their case.
I haven't reproduced the linker error yet since I upgraded so I can't confirm if the case was the cause of my issue or not.
