### ISSUE TITLE
How much caching is actually done?

### ISSUE THREAD

**Issue by manu-st** [playscale/stashed.io#18]
Let's say I have 2 versions of a header files on two machines where stashed.io is installed. The header file being used in most C++ files, changing it will cause a recompilation of all C++ module.

If I compile on machine A first, this will populate the cache. If I then compile on machine B, it will also populate the cache.

Now if I go back to machine A and assuming I have enough space for the caching, will stashed.io have cached the 2 different versions of my .obj files or just the latest one that was compiled?

**Comment by jsmouret** [comment]
It should cache as many versions as possible until the cache is full. Old versions are evicted using a simple LRU (least recent used) algorithm.

With distributed cache, it works pretty much the same way.  It will ask peers if they have that version (remote hit), and will store it back locally for later use.

Hope that helps
