### ISSUE TITLE
NVCC Support?

### ISSUE THREAD

**Issue by peterjc123** [playscale/stashed.io#20]
I wonder whether this supports nvcc on Windows, which uses `cl.exe` as the underlying compiler. CUDA builds cost very long time on Windows, so if this one could be supported, the build time could be shortened a lot.

**Comment by jsmouret** [comment]
It seems to be working out of the box.
We don't replace `nvcc`, but files seem to get properly cached when `nvcc` calls `cl.exe`.

Thanks

**Comment by peterjc123** [comment]
@jsmouret Great! Thanks for your reply.
