### ISSUE TITLE
Stashed 1.4.9 service stops working after upgrading to VS 2019 16.7.2

### ISSUE THREAD

**Issue by cdgray** [playscale/stashed.io#34]
After upgrading VS 2019 to 16.7.2, stash can't connect to server, it show following msg when compiling code,
"Warning: Stashed service is not available. This will not be accelerated. Is the service running?".
I decide to re-install it. During the uninstallation, it stuck at stop service step and I manually end the "stashed-service.exe" service.

Same problem happens again when I install it, this time, after long time waiting, it popup a dialog says,
"Service 'Stashed Service'(Stashed) failed to start. Verify that you have sufficient privileges to start system services."
The installation can't proceed. Even the rollback action can't continue until I manually kill the "stashed-service.exe" service.

Hope you could provide some help on this issue. Thank you.

**Comment by cdgray** [comment]
The problem is solved. 
Uninstall Stash, revert cl.orignal.exe, upgrade VS, then re-install Stash.

**Comment by ryanizer** [comment]
@cdgray can you elaborate on 'revert cl.original.exe' -- do you mean delete existing cl.exe and rename cl.original.exe to cl.exe?
