### ISSUE TITLE
Selective cache purge?

### ISSUE THREAD

**Issue by serge-nikulin** [playscale/stashed.io#5]
My cache slowly grows up and is at ~60GB now.  
I wonder, is it possible to purge blobs corresponding to non-existent folders?  
Also purge by creation date, e.g. ```ctime``` less than some selected time?

Thanks!

**Comment by jsmouret** [comment]
The blobs don't contain their original path (as they can represent stdout/stderr outputs too), but their ctime is updated. The least recently used blobs are removed when the cache size limit is reached.

The best way is to adjust the maximum size of the cache on the dashboard, and it should automagically work :)

**Comment by serge-nikulin** [comment]
Sometimes I overthink :)
Thanks!
