### ISSUE TITLE
Add details for unsupported jobs

### ISSUE THREAD

**Issue by manu-st** [playscale/stashed.io#9]
It would be nice to tell why a job is unsupported. We have many options and trying to enable/disable each of them to see which one is the culprit is cumbersome. It would be nice if it would show in the logs.

**Comment by jsmouret** [comment]
Right now, only the combo PCH+PDB triggers a unsupported job, as described in the [wiki](https://github.com/playscale/stashed.io/wiki/Stats#job-unsupported).

The other unsupported flags will show up as an error in the logs (because we plan on fixing those).

Thanks
